# Generated by Django 3.2.25 on 2026-08-10 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_portal', '0003_applicant_customer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantMessageOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('log', 'Log only')], default='log', max_length=16)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Applicant message outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warn', 'Warning')], default='info', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='onlineapplication',
            name='applicant_p_applica_b0c7d3_idx',
        ),
        migrations.AddField(
            model_name='applicantaccount',
            name='customer_profile_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Last CBS/mock customer lookup payload (name, phone hints, etc.).'),
        ),
        migrations.AddField(
            model_name='applicantaccount',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantportalsettings',
            name='require_customer_lookup',
            field=models.BooleanField(default=False, help_text='If on, registration fails when core-banking customer lookup returns no match (uses live CBS when configured; mock profiles offline).'),
        ),
        migrations.AddField(
            model_name='applicantportalsettings',
            name='require_terms_acceptance',
            field=models.BooleanField(default=True, help_text='Require applicants to accept terms of use on registration.'),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='chapa_checkout_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='chapa_tx_ref',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='withdraw_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicantaccount',
            name='customer_number',
            field=models.CharField(db_index=True, help_text='Core banking customer ID — registration + login (phone or this number).', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='applicantauthevent',
            name='event_type',
            field=models.CharField(choices=[('register', 'Registered'), ('login_success', 'Login success'), ('login_failed', 'Login failed'), ('login_locked', 'Login locked'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('password_reset_request', 'Password reset requested'), ('password_reset_ok', 'Password reset completed'), ('session_timeout', 'Session idle timeout')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('failed', 'Failed')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='onlineapplication',
            index=models.Index(fields=['applicant', 'status'], name='applicant_p_applica_3ec3a1_idx'),
        ),
        migrations.AddField(
            model_name='applicantpasswordreset',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='applicant_portal.applicantaccount'),
        ),
        migrations.AddField(
            model_name='applicantnotification',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applicant_portal.applicantaccount'),
        ),
        migrations.AddField(
            model_name='applicantnotification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='applicant_portal.onlineapplication'),
        ),
    ]
