# Generated by Django 3.2.25 on 2026-08-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_portal', '0004_digital_apply_gaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantportalsettings',
            name='require_customer_lookup',
            field=models.BooleanField(default=False, help_text='If on (or when DECSI_BASE_URL is set live), registration requires a successful customer-number match in core banking before an account can be created.'),
        ),
    ]
