# Generated by Django 3.2.25 on 2026-09-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0093_auto_20260907_2007'),
        ('applicant_portal', '0007_document_quality_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='kyc_identity_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_application', to='loans.kycidentitycase'),
        ),
        migrations.AlterField(
            model_name='applicantportalsettings',
            name='require_customer_lookup',
            field=models.BooleanField(default=False, help_text='If on (or when BANK_CBS_BASE_URL / DECSI_BASE_URL is set live), registration requires a successful customer-number match in core banking before an account can be created.'),
        ),
        migrations.AlterField(
            model_name='onlineapplicationdocument',
            name='auth_status',
            field=models.CharField(choices=[('pending', 'Pending checks'), ('auto_passed', 'Auto-passed (integrity OK)'), ('needs_review', 'Needs manual review'), ('verified', 'Verified authentic'), ('rejected', 'Rejected / not authentic')], default='pending', max_length=20),
        ),
    ]
