# Generated by Django 3.2.25 on 2026-09-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_portal', '0008_auto_20260907_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineapplicationdocument',
            name='auth_status',
            field=models.CharField(choices=[('pending', 'Pending checks'), ('auto_passed', 'Auto-passed (integrity OK)'), ('needs_review', 'Needs manual review'), ('rejected', 'Rejected / not authentic')], default='pending', max_length=20),
        ),
    ]
