# Generated by Django 3.2.25 on 2026-08-06 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0058_agent_conversation_story'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(choices=[('dealer', 'Dealer'), ('agent', 'Agent / promoter'), ('cooperative', 'Cooperative / SACCO'), ('supplier', 'Supplier'), ('other', 'Other partner')], db_index=True, default='dealer', max_length=30)),
                ('code', models.CharField(blank=True, help_text='Optional branch internal code.', max_length=40)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('tin_number', models.CharField(blank=True, max_length=40)),
                ('product_lines', models.CharField(blank=True, help_text='e.g. fertilizer, solar, appliances.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='loans.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_created', to=settings.AUTH_USER_MODEL)),
                ('linked_loan_request', models.ForeignKey(blank=True, help_text='Optional link when the partner is also a borrower.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_partners', to='loans.loanrequest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('activity_kind', models.CharField(choices=[('visit', 'Site visit'), ('sales', 'Sales / order'), ('enquiry', 'Enquiry / lead'), ('collection', 'Collection / payment'), ('training', 'Training / BDS'), ('follow_up', 'Follow-up'), ('other', 'Other')], db_index=True, default='visit', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=2, help_text='ETB when sales / collection are recorded.', max_digits=14, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=40)),
                ('product_mentioned', models.CharField(blank=True, max_length=120)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('site_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('site_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Denormalized for filtering; mirrors partner.branch.', on_delete=django.db.models.deletion.PROTECT, related_name='partner_activities', to='loans.branch')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='partners.partner')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_activities_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'partner activities',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partneractivity',
            index=models.Index(fields=['branch', 'activity_date'], name='partners_pa_branch__5ceaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='partneractivity',
            index=models.Index(fields=['partner', 'activity_date'], name='partners_pa_partner_4fcd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='partneractivity',
            index=models.Index(fields=['activity_kind', 'activity_date'], name='partners_pa_activit_bc8d48_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['branch', 'is_active', 'name'], name='partners_pa_branch__231c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['branch', 'partner_type'], name='partners_pa_branch__809b8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='partners_unique_name_per_branch'),
        ),
    ]
