# Generated by Django 3.2.25 on 2026-08-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_portal_optional_branch'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='marketactor',
            name='partners_ma_br_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketactor',
            name='partners_ma_br_kind_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketactor',
            name='partners_ma_trust_focus_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketobservation',
            name='partners_ma_branch__obsdate_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketobservation',
            name='partners_ma_city_asset_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketobservation',
            name='partners_ma_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketobservation',
            name='partners_ma_actor_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketpriceband',
            name='partners_ma_city_sw_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketpriceband',
            name='partners_ma_city_item_idx',
        ),
        migrations.AddIndex(
            model_name='marketactor',
            index=models.Index(fields=['branch', 'is_active', 'name'], name='partners_ma_branch__54ee80_idx'),
        ),
        migrations.AddIndex(
            model_name='marketactor',
            index=models.Index(fields=['branch', 'actor_kind'], name='partners_ma_branch__d0748f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketactor',
            index=models.Index(fields=['trust_status', 'product_focus'], name='partners_ma_trust_s_a6a986_idx'),
        ),
        migrations.AddIndex(
            model_name='marketobservation',
            index=models.Index(fields=['branch', 'observed_at'], name='partners_ma_branch__80cb26_idx'),
        ),
        migrations.AddIndex(
            model_name='marketobservation',
            index=models.Index(fields=['city', 'asset_class', 'observed_at'], name='partners_ma_city_id_bfbf3f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketobservation',
            index=models.Index(fields=['status', 'observed_at'], name='partners_ma_status_01487f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketobservation',
            index=models.Index(fields=['market_actor', 'observed_at'], name='partners_ma_market__83def0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketpriceband',
            index=models.Index(fields=['city', 'sub_work', 'sub_sub_work'], name='partners_ma_city_id_b53403_idx'),
        ),
        migrations.AddIndex(
            model_name='marketpriceband',
            index=models.Index(fields=['city', 'item_key'], name='partners_ma_city_id_d681fd_idx'),
        ),
    ]
