# loans/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('create_user/', views.create_user, name='create_user'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('create_loan_request/', views.create_loan_request, name='create_loan_request'),
    path('loan_request/<int:loan_request_id>/documents/', views.upload_loan_request_documents, name='upload_loan_request_documents'),
    path('loan_request/<int:loan_request_id>/request_document/', views.request_loan_document, name='request_loan_document'),
    path('loan_request/<int:loan_request_id>/proceed_to_collateral/', views.proceed_to_collateral, name='proceed_to_collateral'),
    path('loan_request/<int:loan_request_id>/appraisal/', views.loan_appraisal_edit, name='loan_appraisal_edit'),
    path('loan_appraisal_steps/', views.loan_appraisal_steps, name='loan_appraisal_steps'),
    path('view_loan_requests/', views.view_loan_requests, name='view_loan_requests'),
    path('view_loan_requests_operation_manager/', views.view_loan_requests_operation_manager, name='view_loan_requests_operation_manager'),
    path('view_loan_requests_finance_manager/', views.view_loan_requests_finance_manager, name='view_loan_requests_finance_manager'),
    path('view_loan_requests_manager/', views.view_loan_requests_manager, name='view_loan_requests_manager'),
    path('loan_request_detail/<int:loan_request_id>/', views.loan_request_detail, name='loan_request_detail'),
    path('assign_loan_officer/<int:loan_request_id>/', views.assign_loan_officer, name='assign_loan_officer'),
    path('send_to_engineering_head/<int:loan_request_id>/', views.send_to_engineering_head, name='send_to_engineering_head'),
    path('loans_sent_for_collateral/', views.loans_sent_for_collateral, name='loans_sent_for_collateral'),
    path('assign_engineer/<int:loan_request_id>/', views.assign_engineer, name='assign_engineer'),
    path('collateral_estimation_config/', views.collateral_estimation_config, name='collateral_estimation_config'),
    path('loan_request_detail_operation_manager/<int:loan_request_id>/', views.loan_request_detail_operation_manager, name='loan_request_detail_operation_manager'),
    path('loan_request_detail_finance/<int:loan_request_id>/', views.loan_request_detail_finance, name='loan_request_detail_finance'),
    path('loan_request_detail_manager/<int:loan_request_id>/', views.loan_request_detail_manager, name='loan_request_detail_manager'),
    path('update_operation_manager_approval/<int:loan_request_id>/', views.update_operation_manager_approval, name='update_operation_manager_approval'),
    path('update_finance_manager_approval/<int:loan_request_id>/', views.update_finance_manager_approval, name='update_finance_manager_approval'),
    path('filter_loan_requests/', views.filter_loan_requests, name='filter_loan_requests'),
    path('manage_districts/', views.manage_districts, name='manage_districts'),
    path('edit_district/<int:district_id>/', views.edit_district, name='edit_district'),
    path('manage_regions/', views.manage_regions, name='manage_regions'),
    path('edit_region/<int:region_id>/', views.edit_region, name='edit_region'),
    path('manage_geo_zones/', views.manage_geo_zones, name='manage_geo_zones'),
    path('edit_geo_zone/<int:zone_id>/', views.edit_geo_zone, name='edit_geo_zone'),
    path('manage_cities/', views.manage_cities, name='manage_cities'),
    path('edit_city/<int:city_id>/', views.edit_city, name='edit_city'),
    path('manage_branches/', views.manage_branches, name='manage_branches'),
    path('edit_branch/<int:branch_id>/', views.edit_branch, name='edit_branch'),
    path('manage_loan_categories/', views.manage_loan_categories, name='manage_loan_categories'),
    path('edit_loan_category/<int:category_id>/', views.edit_loan_category, name='edit_loan_category'),
    path('manage_collateral_types/', views.manage_collateral_types, name='manage_collateral_types'),
    path('edit_collateral_type/<int:collateral_type_id>/', views.edit_collateral_type, name='edit_collateral_type'),
    path('manage_loan_application_document_types/', views.manage_loan_application_document_types, name='manage_loan_application_document_types'),
    path('edit_loan_application_document_type/<int:document_type_id>/', views.edit_loan_application_document_type, name='edit_loan_application_document_type'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),
    path('ajax/load-branches_op/', views.load_branches_op, name='ajax_load_branches_op'),
    path('ajax/load-zones-by-region/', views.load_zones_by_region, name='ajax_load_zones_by_region'),
    path('ajax/load-cities-by-zone/', views.load_cities_by_zone, name='ajax_load_cities_by_zone'),
    path('view_report/', views.view_report, name='view_report'),
    path('generate_report/', views.generate_report, name='generate_report'),
    path('view_report_options/', views.view_report_options, name='view_report_options'),
    path('upload_zones/', views.upload_zones, name='upload_zones'),
    path('upload_branches/', views.upload_branches, name='upload_branches'),
    path('upload_loan_categories/', views.upload_loan_categories, name='upload_loan_categories'),
    path('upload_users/', views.upload_users, name='upload_users'),
    path('upload_loan_requests/', views.upload_loan_requests, name='upload_loan_requests'),
    path('upload_collaterals/', views.upload_collaterals, name='upload_collaterals'),
]
