# loans/urls.py

from django.urls import path
from . import views
from . import views_credit_intelligence as ci_views
from . import views_agent
from . import views_delegation
from . import views_risk
from . import views_cooperative
from . import views_book
from . import views_compliance
from . import views_policy
from applicant_portal import hub_views as applicant_hub_views

urlpatterns = [
    path('', views.home, name='home'),
    path('classic-home/', views.classic_home, name='classic_home'),
    path('risk/', views_risk.risk_desk, name='risk_desk'),
    path(
        'risk/loans/<int:loan_request_id>/review/',
        views_risk.save_risk_review,
        name='save_risk_review',
    ),
    path('compliance/', views_compliance.compliance_desk, name='compliance_desk'),
    path('compliance/open/', views_compliance.compliance_open_manual_case, name='compliance_open_manual_case'),
    path('compliance/cases/<int:case_id>/', views_compliance.compliance_case_detail, name='compliance_case_detail'),
    path('compliance/cases/<int:case_id>/action/', views_compliance.compliance_case_action, name='compliance_case_action'),
    path('monitoring/', views_book.monitoring_desk, name='monitoring_desk'),
    path(
        'monitoring/<int:loan_request_id>/',
        views_book.monitoring_loan,
        name='monitoring_loan',
    ),
    path(
        'monitoring/<int:loan_request_id>/visit/',
        views_book.monitoring_add_visit,
        name='monitoring_add_visit',
    ),
    path(
        'monitoring/<int:loan_request_id>/covenant/<int:condition_id>/',
        views_book.monitoring_covenant_toggle,
        name='monitoring_covenant_toggle',
    ),
    path(
        'monitoring/<int:loan_request_id>/watchlist/',
        views_book.monitoring_watchlist,
        name='monitoring_watchlist',
    ),
    path('collections/', views_book.collections_desk, name='collections_desk'),
    path(
        'collections/<int:loan_request_id>/',
        views_book.collections_loan,
        name='collections_loan',
    ),
    path(
        'collections/<int:loan_request_id>/action/',
        views_book.collections_add_action,
        name='collections_add_action',
    ),
    path(
        'collections/<int:loan_request_id>/arrears/',
        views_book.collections_set_arrears,
        name='collections_set_arrears',
    ),
    path(
        'collections/<int:loan_request_id>/workout/',
        views_book.collections_workout,
        name='collections_workout',
    ),
    path(
        'collections/<int:loan_request_id>/writeoff/',
        views_book.collections_writeoff,
        name='collections_writeoff',
    ),
    path(
        'cooperative/performance/',
        views_cooperative.cooperative_performance,
        name='cooperative_performance',
    ),
    path('agent/', views_agent.agent_assist_console, name='agent_assist'),
    path('agent/chat/', views_agent.agent_chat_api, name='agent_chat_api'),
    path(
        'agent/conversations/<int:conversation_id>/',
        views_agent.agent_conversation_api,
        name='agent_conversation_api',
    ),
    path('agent/runs/<int:run_id>/', views_agent.agent_run_detail, name='agent_run_detail'),
    path(
        'credit-intelligence/',
        ci_views.credit_intelligence_overview,
        name='credit_intelligence_overview',
    ),
    path('credit-intelligence/insights/', ci_views.ci_insights, name='ci_insights'),
    path('credit-intelligence/officer/', ci_views.ci_officer, name='ci_officer'),
    path('credit-intelligence/manager/', ci_views.ci_manager, name='ci_manager'),
    path('credit-intelligence/portfolio/', ci_views.ci_portfolio, name='ci_portfolio'),
    path('credit-intelligence/collateral/', ci_views.ci_collateral, name='ci_collateral'),
    path('credit-intelligence/assistant/', ci_views.ci_assistant, name='ci_assistant'),
    path(
        'api/credit-intelligence/overview/',
        ci_views.credit_intelligence_overview_api,
        name='api_credit_intelligence_overview',
    ),
    path(
        'api/credit-intelligence/assistant/',
        ci_views.ci_assistant_api,
        name='api_ci_assistant',
    ),
    path(
        'api/credit-intelligence/applications/<int:loan_request_id>/decision/',
        ci_views.ci_application_decision_api,
        name='api_ci_application_decision',
    ),
    path('create_user/', views.create_user, name='create_user'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('create_loan_request/', views.create_loan_request, name='create_loan_request'),
    path('ajax/customer_lookup/', views.ajax_staff_lookup_customer, name='ajax_staff_lookup_customer'),
    path('delegations/', views_delegation.manage_delegations, name='manage_delegations'),
    path('delegations/<int:delegation_id>/approve/', views_delegation.approve_delegation, name='approve_delegation'),
    path('delegations/<int:delegation_id>/reject/', views_delegation.reject_delegation, name='reject_delegation'),
    path('delegations/<int:delegation_id>/revoke/', views_delegation.revoke_delegation, name='revoke_delegation'),
    path('loan_request/<int:loan_request_id>/documents/', views.upload_loan_request_documents, name='upload_loan_request_documents'),
    path('loan_request/<int:loan_request_id>/request_document/', views.request_loan_document, name='request_loan_document'),
    path(
        'loan_request/<int:loan_request_id>/documents/<int:document_id>/view/',
        views.view_loan_document,
        name='view_loan_document',
    ),
    path(
        'loan_request/<int:loan_request_id>/documents/<int:document_id>/authenticate/',
        views.authenticate_loan_document,
        name='authenticate_loan_document',
    ),
    path(
        'loan_request/<int:loan_request_id>/documents/<int:document_id>/file/',
        views.serve_loan_document_inline,
        name='serve_loan_document_inline',
    ),
    path('loan_request/<int:loan_request_id>/proceed_to_collateral/', views.proceed_to_collateral, name='proceed_to_collateral'),
    path('loan_request/<int:loan_request_id>/appraisal/', views.loan_appraisal_edit, name='loan_appraisal_edit'),
    path('loan_request/<int:loan_request_id>/appraisal/step/<int:step>/', views.loan_appraisal_step, name='loan_appraisal_step'),
    path(
        'loan_request/<int:loan_request_id>/appraisal/features.json',
        views.appraisal_features_json,
        name='appraisal_features_json',
    ),
    path('loan_appraisal_steps/', views.loan_appraisal_steps, name='loan_appraisal_steps'),
    path('view_loan_requests/', views.view_loan_requests, name='view_loan_requests'),
    path('view_loan_requests_operation_manager/', views.view_loan_requests_operation_manager, name='view_loan_requests_operation_manager'),
    path('view_loan_requests_finance_manager/', views.view_loan_requests_finance_manager, name='view_loan_requests_finance_manager'),
    path('view_loan_requests_manager/', views.view_loan_requests_manager, name='view_loan_requests_manager'),
    path('loan_request_detail/<int:loan_request_id>/', views.loan_request_detail, name='loan_request_detail'),
    path('assign_loan_officer/<int:loan_request_id>/', views.assign_loan_officer, name='assign_loan_officer'),
    path('send_to_engineering_head/<int:loan_request_id>/', views.send_to_engineering_head, name='send_to_engineering_head'),
    path('loans_sent_for_collateral/', views.loans_sent_for_collateral, name='loans_sent_for_collateral'),
    path('assign_engineer/<int:loan_request_id>/', views.assign_engineer, name='assign_engineer'),
    path('collateral_estimation_config/', views.collateral_estimation_config, name='collateral_estimation_config'),
    path('loan_request_detail_operation_manager/<int:loan_request_id>/', views.loan_request_detail_operation_manager, name='loan_request_detail_operation_manager'),
    path('loan_request_detail_finance/<int:loan_request_id>/', views.loan_request_detail_finance, name='loan_request_detail_finance'),
    path('loan_request_detail_manager/<int:loan_request_id>/', views.loan_request_detail_manager, name='loan_request_detail_manager'),
    path(
        'loan_request/<int:loan_request_id>/submit_to_committee/',
        views.submit_to_committee,
        name='submit_to_committee',
    ),
    path(
        'loan_request/<int:loan_request_id>/committee_vote/',
        views.cast_committee_vote,
        name='cast_committee_vote',
    ),
    path(
        'loan_request/<int:loan_request_id>/return_to_officer/',
        views.return_loan_to_officer_view,
        name='return_loan_to_officer',
    ),
    path(
        'loan_request/<int:loan_request_id>/committee_appraisal/',
        views.committee_appraisal_pack,
        name='committee_appraisal_pack',
    ),
    path(
        'loan_request/<int:loan_request_id>/appraisal_pack.xlsx',
        views.export_appraisal_pack_excel,
        name='export_appraisal_pack_excel',
    ),
    path(
        'loan_request/<int:loan_request_id>/appraisal_pack.pdf',
        views.export_appraisal_pack_pdf,
        name='export_appraisal_pack_pdf',
    ),
    path('post_approval/', views.post_approval_queue, name='post_approval_queue'),
    path(
        'loan_request/<int:loan_request_id>/post_approval/',
        views.post_approval_detail,
        name='post_approval_detail',
    ),
    path(
        'loan_request/<int:loan_request_id>/audit_pack.zip',
        views.loan_audit_pack_zip,
        name='loan_audit_pack_zip',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/condition/<int:condition_id>/',
        views.post_approval_condition_toggle,
        name='post_approval_condition_toggle',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/regen_schedule/',
        views.post_approval_regen_schedule,
        name='post_approval_regen_schedule',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/confirm_schedule/',
        views.post_approval_confirm_schedule,
        name='post_approval_confirm_schedule',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/mark_ready/',
        views.post_approval_mark_ready,
        name='post_approval_mark_ready',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/mark_disbursed/',
        views.post_approval_mark_disbursed,
        name='post_approval_mark_disbursed',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/verify_equity/',
        views.post_approval_verify_equity,
        name='post_approval_verify_equity',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/add_tranche/',
        views.post_approval_add_tranche,
        name='post_approval_add_tranche',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/collateral_flags/',
        views.post_approval_collateral_flags,
        name='post_approval_collateral_flags',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/collateral_legal/upload/',
        views.post_approval_collateral_legal_upload,
        name='post_approval_collateral_legal_upload',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/collateral_legal/<int:doc_id>/verify/',
        views.post_approval_collateral_legal_verify,
        name='post_approval_collateral_legal_verify',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/agreement/generate/',
        views.post_approval_agreement_generate,
        name='post_approval_agreement_generate',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/agreement/<int:agreement_id>/sign/',
        views.post_approval_agreement_sign,
        name='post_approval_agreement_sign',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/agreement/<int:agreement_id>/print/',
        views.post_approval_agreement_print,
        name='post_approval_agreement_print',
    ),
    path(
        'loan_request/<int:loan_request_id>/post_approval/agreement/<int:agreement_id>/pdf/',
        views.post_approval_agreement_pdf,
        name='post_approval_agreement_pdf',
    ),
    path('notifications/', views.loan_notifications_list, name='loan_notifications_list'),
    path(
        'notifications/<int:notification_id>/read/',
        views.loan_notification_mark_read,
        name='loan_notification_mark_read',
    ),
    path('update_operation_manager_approval/<int:loan_request_id>/', views.update_operation_manager_approval, name='update_operation_manager_approval'),
    path('update_finance_manager_approval/<int:loan_request_id>/', views.update_finance_manager_approval, name='update_finance_manager_approval'),
    path('filter_loan_requests/', views.filter_loan_requests, name='filter_loan_requests'),
    path('manage_districts/', views.manage_districts, name='manage_districts'),
    path('edit_district/<int:district_id>/', views.edit_district, name='edit_district'),
    path('manage_departments/', views.manage_departments, name='manage_departments'),
    path('edit_department/<int:department_id>/', views.edit_department, name='edit_department'),
    path('manage_regions/', views.manage_regions, name='manage_regions'),
    path('edit_region/<int:region_id>/', views.edit_region, name='edit_region'),
    path('manage_geo_zones/', views.manage_geo_zones, name='manage_geo_zones'),
    path('edit_geo_zone/<int:zone_id>/', views.edit_geo_zone, name='edit_geo_zone'),
    path('manage_cities/', views.manage_cities, name='manage_cities'),
    path('edit_city/<int:city_id>/', views.edit_city, name='edit_city'),
    path('manage_branches/', views.manage_branches, name='manage_branches'),
    path('edit_branch/<int:branch_id>/', views.edit_branch, name='edit_branch'),
    path('manage_loan_categories/', views.manage_loan_categories, name='manage_loan_categories'),
    path('edit_loan_category/<int:category_id>/', views.edit_loan_category, name='edit_loan_category'),
    path(
        'manage_loan_category/<int:category_id>/documents/',
        views.manage_loan_category_documents,
        name='manage_loan_category_documents',
    ),
    path('manage_collateral_types/', views.manage_collateral_types, name='manage_collateral_types'),
    path('edit_collateral_type/<int:collateral_type_id>/', views.edit_collateral_type, name='edit_collateral_type'),
    path('manage_approval_committees/', views.manage_approval_committees, name='manage_approval_committees'),
    path('add_approval_committee_level/', views.add_approval_committee_level, name='add_approval_committee_level'),
    path(
        'edit_approval_committee_level/<int:level_id>/',
        views.edit_approval_committee_level,
        name='edit_approval_committee_level',
    ),
    path(
        'delete_approval_committee_level/<int:level_id>/',
        views.delete_approval_committee_level,
        name='delete_approval_committee_level',
    ),
    path('manage_loan_application_document_types/', views.manage_loan_application_document_types, name='manage_loan_application_document_types'),
    path(
        'manage_process_policy/',
        views_policy.manage_process_policy,
        name='manage_process_policy',
    ),
    path(
        'manage_applicant_portal/',
        applicant_hub_views.manage_applicant_portal_settings,
        name='manage_applicant_portal_settings',
    ),
    path(
        'online_loan_intake/',
        applicant_hub_views.online_loan_intake,
        name='online_loan_intake',
    ),
    path('edit_loan_application_document_type/<int:document_type_id>/', views.edit_loan_application_document_type, name='edit_loan_application_document_type'),
    path(
        'document_type/<int:document_type_id>/reference_sample/file/',
        views.serve_document_type_reference_sample,
        name='serve_document_type_reference_sample',
    ),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),
    path('ajax/load-branches_op/', views.load_branches_op, name='ajax_load_branches_op'),
    path('ajax/load-zones-by-region/', views.load_zones_by_region, name='ajax_load_zones_by_region'),
    path('ajax/load-cities-by-zone/', views.load_cities_by_zone, name='ajax_load_cities_by_zone'),
    path('view_report/', views.view_report, name='view_report'),
    path('generate_report/', views.generate_report, name='generate_report'),
    path('view_report_options/', views.view_report_options, name='view_report_options'),
    path('reports/branch_dashboard/', views.branch_report_dashboard, name='branch_report_dashboard'),
    path('upload_zones/', views.upload_zones, name='upload_zones'),
    path('upload_branches/', views.upload_branches, name='upload_branches'),
    path('upload_loan_categories/', views.upload_loan_categories, name='upload_loan_categories'),
    path('upload_users/', views.upload_users, name='upload_users'),
    path('upload_loan_requests/', views.upload_loan_requests, name='upload_loan_requests'),
    path('upload_collaterals/', views.upload_collaterals, name='upload_collaterals'),
]
