# Generated by Django 3.2.25 on 2026-02-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0003_unit_price_sub_sub_work_and_order_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subworkunitprice',
            options={'verbose_name_plural': 'SubSubWork unit prices'},
        ),
    ]
