# Generated by Django 3.2.25 on 2026-03-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0005_unit_price_and_valuation_sub_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subworkunitprice',
            options={'verbose_name_plural': 'SubWork / SubSubWork unit prices'},
        ),
    ]
