# Generated by Django 3.2.25 on 2025-09-15 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('loan_officer', 'Branch Manager'), ('finance', 'Finance'), ('operational_manager', 'Operational Manager'), ('manager', 'Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
