# Generated by Django 3.2.25 on 2025-09-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('loan_officer', 'Branch Manager'), ('finance', 'Finance'), ('operational_manager', 'Operational Manager'), ('manager', 'Manager')], max_length=20),
        ),
    ]
