# Generated by Django 3.2.25 on 2024-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestLoanRequestID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_id', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_request_id',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
