# Generated by Django 3.2.25 on 2025-09-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
