# Generated by Django 3.2.25 on 2025-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20250915_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='customer_number',
            field=models.CharField(default=20001010, max_length=50),
            preserve_default=False,
        ),
    ]
