# Generated by Django 3.2.25 on 2025-09-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanrequest_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='customer_number',
        ),
    ]
