# Generated by Django 3.2.25 on 2025-09-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanrequest_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
