# Generated by Django 3.2.25 on 2025-09-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loanrequest_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('finance', 'Finance'), ('operational_manager', 'Operational Manager'), ('manager', 'Manager')], max_length=20),
        ),
    ]
