# Generated by Django 3.2.25 on 2026-03-02 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loanrequest_assigned_loan_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='assigned_loan_officer',
            field=models.ForeignKey(blank=True, help_text='Loan officer assigned by branch manager for analysis and collateral estimation.', limit_choices_to={'role': 'loan_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loan_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
