# Generated by Django 3.2.25 on 2026-03-06 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_collateral_estimation_config_and_sent_to_engineering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, help_text='Engineer assigned by engineering head for collateral estimation (when mode is Engineering Team).', limit_choices_to={'role': 'engineer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_engineer_loan_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
