# Generated by Django 3.2.25 on 2026-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_alter_loanrequest_assigned_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateralestimationconfig',
            name='mode',
            field=models.CharField(choices=[('loan_officer', 'Loan Officer (branch manager assigns loan officer)'), ('engineering_team', 'Engineering Team (branch manager sends to engineering head; engineering head assigns engineer)'), ('both', 'Both (loan officers and engineering team can both be used)')], default='loan_officer', help_text='Who performs collateral estimation: loan officer, engineering team, or both.', max_length=20),
        ),
    ]
