# Generated by Django 3.2.25 on 2026-03-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_appraisal_sheets_4_5_6_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalamortizationentry',
            name='period_number',
            field=models.PositiveIntegerField(help_text='Payment number.'),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='amount_approved',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by committee (if different from requested).', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='collateral_coverage_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Collateral coverage (total collateral / loan amount).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='collateral_guarantors_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Guarantors value.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='collateral_immovable_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Immovable (land/buildings) value.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='collateral_intangible_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Intangible / securities / contracts value.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='collateral_moveable_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Moveable / fixed deposits value.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='committee_comments',
            field=models.TextField(blank=True, help_text='Credit committee comments.', null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='es_eligibility_decision',
            field=models.CharField(blank=True, choices=[('pass', 'PASS'), ('pass_action', 'PASS WITH ACTION POINTS'), ('reject', 'REJECT')], help_text='Decision on eligibility: PASS / PASS WITH ACTION POINTS / REJECT.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='es_notes',
            field=models.TextField(blank=True, help_text='E&S checklist summary / action points.', null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='es_risk_category',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='E&S risk category.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='rate_approved',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate approved (%).', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='strengths',
            field=models.TextField(blank=True, help_text='Key strengths.', null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='term_approved_months',
            field=models.PositiveIntegerField(blank=True, help_text='Term approved (months).', null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='weaknesses',
            field=models.TextField(blank=True, help_text='Key weaknesses.', null=True),
        ),
    ]
