# Generated by Django 3.2.25 on 2026-03-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_auto_20260316_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequestbasicinfo',
            name='economic_sector',
            field=models.CharField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Trade', 'Trade'), ('Service', 'Service'), ('Construction', 'Construction'), ('Agriculture', 'Agriculture')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequestbasicinfo',
            name='education_level',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('College', 'College'), ('BA and above', 'BA and above')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequestbasicinfo',
            name='form_of_ownership',
            field=models.CharField(blank=True, choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('PLC', 'PLC'), ('Partnership', 'Partnership'), ('Association', 'Association'), ('Share Company', 'Share Company')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequestbasicinfo',
            name='interest_basis',
            field=models.CharField(blank=True, choices=[('Declining', 'Declining'), ('Flat', 'Flat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequestbasicinfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequestbasicinfo',
            name='repayment_frequency',
            field=models.CharField(blank=True, choices=[('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annual', 'Semi-annual'), ('Annual', 'Annual')], max_length=50, null=True),
        ),
    ]
