# Generated by Django 3.2.25 on 2026-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_auto_20260317_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalcredithistoryentry',
            name='letter_from_lender',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appraisalcredithistoryentry',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Working capital', 'Working capital'), ('Fixed Asset', 'Fixed Asset')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appraisalcredithistoryentry',
            name='repayment',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Irregular', 'Irregular'), ('On time', 'On time'), ('Delayed', 'Delayed')], max_length=100, null=True),
        ),
    ]
