# Generated by Django 3.2.25 on 2026-06-04 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0030_configurable_approval_committees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeeapprovalpolicy',
            options={'verbose_name': 'Committee approval policy (legacy)', 'verbose_name_plural': 'Committee approval policy (legacy)'},
        ),
        migrations.AlterField(
            model_name='appraisaleschecklistitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisaleschecklistitem',
            name='mitigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisaleschecklistitem',
            name='response_yes_no',
            field=models.CharField(blank=True, choices=[('', '—'), ('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='committeeapprovalpolicy',
            name='min_approvals_required',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='committeeapprovalpolicy',
            name='min_declines_required',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='documentauthenticationpolicy',
            name='allowed_extensions',
            field=models.CharField(default='pdf,jpg,jpeg,png,doc,docx', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentauthenticationpolicy',
            name='max_file_size_mb',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='documentauthenticationpolicy',
            name='require_verified_documents_for_collateral',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_annual_dscr_min',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_annual_dscr',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_bureau_defaults',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_bureau_inquiries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_bureau_restructured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_es_high_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_es_reject',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_incomplete_sheets',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_monthly_dscr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_qualitative_fail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_block_stressed_dscr',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_bureau_inquiries_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_monthly_dscr_min',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='hard_stressed_dscr_min',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='require_sheets_complete_before_finish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='warn_annual_dscr_min',
            field=models.DecimalField(decimal_places=4, default=1.2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='warn_bureau_inquiries_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='warn_collateral_coverage_min',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='warn_monthly_dscr_min',
            field=models.DecimalField(decimal_places=4, default=1.2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loananalysispolicyconfig',
            name='warn_stressed_dscr_min',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_active_loans_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_defaults_ever',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_inquiries_6m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_restructured_ever',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_score_band',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('thin', 'Thin file / No bureau')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_thin_file',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_total_monthly_debt_service',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='bureau_total_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_annual_debt_service',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_annual_net_cashflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_cogs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_other_operating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_salaries',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_transport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='cf_monthly_utilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='dscr_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='stress_cost_increase_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='stress_sales_drop_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='stressed_dscr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='stressed_net_monthly_cashflow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='submitted_to_committee_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'loan_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_submitted_to_committee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrequestdocument',
            name='auth_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loanrequestdocument',
            name='automated_checks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='loanrequestdocument',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
