# Generated by Django 3.2.25 on 2026-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0042_collateral_notification_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='declared_address_text',
            field=models.TextField(blank=True, help_text='Cached address text used for geocoding (from Sheet 1).'),
        ),
    ]
