# Generated by Django 3.2.25 on 2026-07-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0045_basicinfo_field_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationdocumenttype',
            name='for_appraisal_mode',
            field=models.CharField(blank=True, choices=[('', 'All modes'), ('msme', 'MSME only'), ('corporate', 'Corporate only')], default='', help_text='Limit this document type to MSME or Corporate loans (blank = both).', max_length=20),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='appraisal_mode',
            field=models.CharField(choices=[('msme', 'MSME / cashflow'), ('corporate', 'Corporate')], db_index=True, default='msme', help_text='MSME vs Corporate sheet content (copied from category at create).', max_length=20),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='bs_current_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='bs_current_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='bs_equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='bs_inventory',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='bs_total_assets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='bs_total_liabilities',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='corp_annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='corp_operating_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='EBIT / operating profit.', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='monthly_cashflow_grid',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='ratio_acid_test',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(Current assets − inventory) / current liabilities.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='ratio_current',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current assets / current liabilities.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanappraisal',
            name='ratio_debt_equity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total liabilities / equity.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='appraisal_mode',
            field=models.CharField(choices=[('msme', 'MSME / cashflow'), ('corporate', 'Corporate')], default='msme', help_text='Which appraisal wizard content to use for loans in this category.', max_length=20),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, help_text='Core banking / Temenos-style customer id for party lookup.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanrequestbasicinfo',
            name='directors_summary',
            field=models.TextField(blank=True, help_text='Directors / board summary.', null=True),
        ),
        migrations.AddField(
            model_name='loanrequestbasicinfo',
            name='legal_registration_number',
            field=models.CharField(blank=True, help_text='Company registration / CR number.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanrequestbasicinfo',
            name='lowest_sales_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Low-season sales as % of average (Excel seasonality).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='loanrequestbasicinfo',
            name='peak_sales_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peak-season sales as % of average (Excel seasonality).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='loanrequestbasicinfo',
            name='ubo_summary',
            field=models.TextField(blank=True, help_text='Ultimate beneficial owners (UBO) summary.', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequestbasicinfo',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AppraisalPurposeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purpose_lines', to='loans.loanrequestbasicinfo')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
