# Generated by Django 3.2.25 on 2026-07-27 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0046_post_cleanup_model_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanappraisal',
            name='es_approved_by',
            field=models.ForeignKey(blank=True, help_text='Loan officer confirmation of E&S eligibility. Credit committee signs the loan decision separately via committee voting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_approved_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='E&S confirmed by (loan officer)'),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='es_checked_by',
            field=models.ForeignKey(blank=True, help_text='Loan officer who checked checklist answers and mitigations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_checked_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='Checked by (loan officer)'),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='es_screened_by',
            field=models.ForeignKey(blank=True, help_text='Loan officer who screened the E&S checklist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_screened_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='Screened by (loan officer)'),
        ),
    ]
