# Generated by Django 3.2.25 on 2026-07-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0050_disbursement_post_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='appraisal_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the assigned loan officer finished appraisal (locks Sheets 1–7 until returned).', null=True),
        ),
    ]
