# Generated by Django 3.2.25 on 2026-07-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0051_alter_loanrequest_appraisal_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='cbs_booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='cbs_booking_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='cbs_booking_status',
            field=models.CharField(blank=True, choices=[('', 'Not booked'), ('mock', 'Mock booked'), ('booked', 'Booked in CBS'), ('failed', 'CBS booking failed'), ('skipped', 'Skipped')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='cbs_loan_account',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='cbs_outstanding_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer outstanding snapshot from CBS at booking time (ETB).', max_digits=20, null=True),
        ),
    ]
