# Generated by Django 3.2.25 on 2026-08-05 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0055_committee_tiebreaker_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalcommitteememberrule',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Administrator'), ('admin', 'System Administrator'), ('engineering_head', 'Engineering Head'), ('engineer', 'Engineer / Valuer'), ('loan_officer', 'Loan Officer'), ('branch_manager', 'Branch Manager'), ('accountant', 'Accountant'), ('district_manager', 'District Manager'), ('cooperative_manager', 'Branch Cooperative Manager'), ('finance_manager', 'Finance Manager'), ('credit_head', 'Credit Department Head'), ('credit_loan_officer', 'Credit Loan Officer'), ('ceo', 'Chief Executive Officer'), ('vp', 'Vice President'), ('vp_operations', 'VP Operations'), ('vp_it', 'VP IT'), ('vp_customer_service', 'VP Customer Service'), ('board_member', 'Board Member'), ('risk_compliance', 'Risk & Compliance Officer'), ('auditor', 'Auditor / Viewer'), ('operation_manager', 'Operation Manager (legacy)'), ('credit_committee', 'Credit Committee Member (legacy)')], help_text='For branch: user must belong to the loan branch. For district: loan district.', max_length=30),
        ),
        migrations.AlterField(
            model_name='branchcommitteememberrule',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Administrator'), ('admin', 'System Administrator'), ('engineering_head', 'Engineering Head'), ('engineer', 'Engineer / Valuer'), ('loan_officer', 'Loan Officer'), ('branch_manager', 'Branch Manager'), ('accountant', 'Accountant'), ('district_manager', 'District Manager'), ('cooperative_manager', 'Branch Cooperative Manager'), ('finance_manager', 'Finance Manager'), ('credit_head', 'Credit Department Head'), ('credit_loan_officer', 'Credit Loan Officer'), ('ceo', 'Chief Executive Officer'), ('vp', 'Vice President'), ('vp_operations', 'VP Operations'), ('vp_it', 'VP IT'), ('vp_customer_service', 'VP Customer Service'), ('board_member', 'Board Member'), ('risk_compliance', 'Risk & Compliance Officer'), ('auditor', 'Auditor / Viewer'), ('operation_manager', 'Operation Manager (legacy)'), ('credit_committee', 'Credit Committee Member (legacy)')], max_length=30),
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ok', 'Completed'), ('error', 'Failed'), ('partial', 'Partial')], default='ok', max_length=20)),
                ('steps', models.JSONField(blank=True, default=list, help_text='Ordered tool results.')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='loans.loanrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent assist run',
                'verbose_name_plural': 'Agent assist runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
