# Generated by Django 3.2.25 on 2026-08-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0062_loanrequest_source_channel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securityauditlog',
            name='loans_secur_event_t_idx',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='customer_profile_snapshot',
            field=models.JSONField(blank=True, help_text='Important core-banking / party API fields (subset) for staff display.', null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationdocumenttype',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Fallback required flag when a loan type has no document pack configured. When a pack exists for a loan category, that pack controls required/optional.'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['event_type', '-created_at'], name='loans_secur_event_t_b0040d_idx'),
        ),
    ]
