# Generated by Django 3.2.25 on 2026-08-13 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0063_loanrequest_customer_profile_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancommitteevote',
            name='cast_by',
            field=models.ForeignKey(blank=True, help_text='If set, this vote was cast by a delegate acting for member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_votes_cast_for_others', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopes', models.JSONField(default=list, help_text='List of scope keys: committee_vote, cooperative_intake, appraisal, …')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_created', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(help_text='User who may act with principal authority.', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(help_text='User whose authority is granted.', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff delegation',
                'verbose_name_plural': 'Staff delegations',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='DelegationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_actions_as_actor', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='loans.staffdelegation')),
                ('loan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_actions', to='loans.loanrequest')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_actions_as_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffdelegation',
            index=models.Index(fields=['delegate', 'is_active', 'starts_at', 'ends_at'], name='loans_staff_delegat_83c039_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdelegation',
            index=models.Index(fields=['principal', 'is_active'], name='loans_staff_princip_41bd77_idx'),
        ),
    ]
