# Generated by Django 3.2.25 on 2026-08-13 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0064_staff_delegation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staffdelegation',
            name='loans_staff_delegat_83c039_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffdelegation',
            name='loans_staff_princip_41bd77_idx',
        ),
        migrations.AddField(
            model_name='staffdelegation',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffdelegation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffdelegation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffdelegation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='staffdelegation',
            name='delegate',
            field=models.ForeignKey(help_text='Proposed / signed user who may act with principal authority.', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffdelegation',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='True only while approved and not revoked (authority gate also checks dates).'),
        ),
        migrations.AddIndex(
            model_name='staffdelegation',
            index=models.Index(fields=['delegate', 'status', 'is_active', 'starts_at', 'ends_at'], name='loans_staff_delegat_fce59a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdelegation',
            index=models.Index(fields=['principal', 'status', 'is_active'], name='loans_staff_princip_80359c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffdelegation',
            index=models.Index(fields=['status', 'created_at'], name='loans_staff_status_80bb35_idx'),
        ),
    ]
