# Generated by Django 3.2.25 on 2026-08-16 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0066_delegation_backfill_approved'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', loans.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='risk_review_note',
            field=models.TextField(blank=True, help_text='Risk & Compliance note on credit / E&S / coverage concerns.'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='risk_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='risk_reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'risk_compliance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_risk_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
