# Generated by Django 3.2.25 on 2026-08-16 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0067_risk_review_and_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='collateral_held_via_poa',
            field=models.BooleanField(default=False, help_text='Collateral is pledged under a Loan Collateral Power of Attorney (POA required).'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='require_collateral_restriction',
            field=models.BooleanField(default=True, help_text='Applicant must bring a government Collateral Restriction paper before disbursement.'),
        ),
        migrations.CreateModel(
            name='LoanCollateralLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('collateral_restriction', 'Collateral Restriction (government)'), ('power_of_attorney', 'Loan Collateral Power of Attorney')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded — pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='uploaded', max_length=16)),
                ('reference_number', models.CharField(blank=True, help_text='Government restriction ref / POA deed number.', max_length=120)),
                ('issuing_office', models.CharField(blank=True, help_text='e.g. Land Administration / Municipality / Notary.', max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('grantor_name', models.CharField(blank=True, help_text='Person/entity granting the Power of Attorney (collateral owner).', max_length=255)),
                ('attorney_name', models.CharField(blank=True, help_text='Attorney-in-fact named in the POA (often the borrower).', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Scan/photo of the restriction paper or POA deed.', null=True, upload_to='collateral_legal/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_legal_documents', to='loans.loanrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_legal_uploads', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_legal_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collateral legal document',
                'verbose_name_plural': 'Collateral legal documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loancollaterallegaldocument',
            index=models.Index(fields=['loan_request', 'kind', 'status'], name='loans_loanc_loan_re_479e3b_idx'),
        ),
    ]
