# Generated by Django 3.2.25 on 2026-08-16 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0068_collateral_legal_restriction_poa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('loan_agreement', 'Loan agreement'), ('collateral_pledge', 'Collateral pledge agreement'), ('guarantee', 'Guarantee agreement')], db_index=True, default='loan_agreement', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body_text', models.TextField(help_text='Agreement text snapshot at generation time.')),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of body_text; signatures bind to this hash.', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signatures', 'Pending signatures'), ('partially_signed', 'Partially signed'), ('fully_signed', 'Fully signed'), ('void', 'Void')], db_index=True, default='draft', max_length=24)),
                ('require_borrower', models.BooleanField(default=True)),
                ('require_guarantor', models.BooleanField(default=False)),
                ('require_officer', models.BooleanField(default=True)),
                ('require_branch_manager', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan agreement',
                'verbose_name_plural': 'Loan agreements',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='require_agreement_signatures',
            field=models.BooleanField(default=True, help_text='Loan agreement must be digitally signed before disbursement.'),
        ),
        migrations.CreateModel(
            name='LoanAgreementSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('borrower', 'Borrower / applicant'), ('guarantor', 'Guarantor'), ('officer', 'Loan officer'), ('branch_manager', 'Branch manager')], db_index=True, max_length=24)),
                ('signer_name', models.CharField(max_length=255)),
                ('signature_image', models.ImageField(help_text='PNG captured from signature pad.', upload_to='agreement_signatures/%Y/%m/')),
                ('content_hash_at_sign', models.CharField(help_text='Must match agreement.content_hash at time of signing.', max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('is_valid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='loans.loanagreement')),
                ('signer_user', models.ForeignKey(blank=True, help_text='Staff user when an officer/BM signs; blank for walk-in borrower.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement signature',
                'verbose_name_plural': 'Agreement signatures',
                'ordering': ['signed_at'],
            },
        ),
        migrations.AddField(
            model_name='loanagreement',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='loans.loanrequest'),
        ),
        migrations.AddConstraint(
            model_name='loanagreementsignature',
            constraint=models.UniqueConstraint(condition=models.Q(('is_valid', True)), fields=('agreement', 'role'), name='loans_unique_valid_signature_per_role'),
        ),
    ]
