# Generated by Django 3.2.25 on 2026-08-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0069_agreement_digital_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreementsignature',
            name='declaration_accepted',
            field=models.BooleanField(default=False, help_text='Signer confirmed they have read the agreement and intend to be bound.'),
        ),
        migrations.AddField(
            model_name='loanagreementsignature',
            name='signer_id_number',
            field=models.CharField(blank=True, help_text='National ID / kebele ID / passport / staff ID shown at signing.', max_length=80),
        ),
        migrations.AddField(
            model_name='loanagreementsignature',
            name='typed_name',
            field=models.CharField(blank=True, help_text='Name typed by the signer to confirm identity (must match signer_name).', max_length=255),
        ),
        migrations.AddField(
            model_name='loancollaterallegaldocument',
            name='parcel_reference',
            field=models.CharField(blank=True, help_text='Plot / parcel / kebele / title deed number.', max_length=160),
        ),
        migrations.AddField(
            model_name='loancollaterallegaldocument',
            name='property_location',
            field=models.CharField(blank=True, help_text='Woreda / kebele / site of the restricted or pledged property.', max_length=255),
        ),
        migrations.AddField(
            model_name='loancollaterallegaldocument',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Staff note recorded when verifying or rejecting.', max_length=400),
        ),
    ]
