# Generated by Django 3.2.25 on 2026-08-21 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0073_process_policy_closing_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanagreementsignature',
            name='pki_certificate_serial',
            field=models.CharField(blank=True, help_text='Reserved: signer certificate serial when PKI qualified e-sign is enabled.', max_length=128),
        ),
        migrations.AddField(
            model_name='loanagreementsignature',
            name='pki_timestamp_token',
            field=models.TextField(blank=True, help_text='Reserved: RFC 3161 / TSP timestamp token for qualified e-sign.'),
        ),
        migrations.AddField(
            model_name='loanagreementsignature',
            name='signature_image_sha256',
            field=models.CharField(blank=True, help_text='SHA-256 of the signature image bytes at capture time.', max_length=64),
        ),
        migrations.AddField(
            model_name='loanagreementsignature',
            name='signature_method',
            field=models.CharField(choices=[('drawn_hash', 'Drawn mark + content hash (branch e-sign)'), ('pki_qualified', 'PKI / qualified e-sign (reserved)')], db_index=True, default='drawn_hash', help_text='drawn_hash = pad image + SHA-256 content binding (current). pki_qualified = reserved for future CA/TSP qualified e-sign.', max_length=24),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('login_locked', 'Account locked'), ('logout', 'Logout'), ('mfa_challenge', 'MFA challenge issued'), ('mfa_success', 'MFA success'), ('mfa_failed', 'MFA failed'), ('mfa_enrolled', 'MFA enrolled'), ('mfa_disabled', 'MFA disabled'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_unlocked', 'User unlocked'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('password_changed', 'Password changed'), ('audit_exported', 'Security audit exported'), ('session_timeout', 'Session idle timeout'), ('loan_audit_pack', 'Loan audit pack exported')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CbsBookingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('mock', 'Mock booked'), ('booked', 'Booked in CBS'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, max_length=16)),
                ('booking_ref', models.CharField(blank=True, default='', max_length=120)),
                ('loan_account', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='Typically loan_request_id — used to detect duplicate booking attempts.', max_length=80)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_raw', models.JSONField(blank=True, default=dict)),
                ('attempted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbs_booking_attempts', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbs_booking_attempts', to='loans.loanrequest')),
            ],
            options={
                'verbose_name': 'CBS booking attempt',
                'verbose_name_plural': 'CBS booking attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
