# Generated by Django 3.2.25 on 2026-08-21 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0074_compliance_audit_pack_cbs_esign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanagreementsignature',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='PNG from signature pad (drawn_hash). Optional for remote_otp.', upload_to='agreement_signatures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='loanagreementsignature',
            name='signature_method',
            field=models.CharField(choices=[('drawn_hash', 'Drawn mark + content hash (branch e-sign)'), ('remote_otp', 'Remote OTP acceptance (SMS link)'), ('pki_qualified', 'PKI / qualified e-sign (reserved)')], db_index=True, default='drawn_hash', help_text='drawn_hash = pad image + SHA-256 content binding (branch). remote_otp = SMS OTP + content hash (remote). pki_qualified = reserved for future CA/TSP qualified e-sign.', max_length=24),
        ),
        migrations.CreateModel(
            name='LoanAgreementRemoteChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('borrower', 'Borrower / applicant'), ('guarantor', 'Guarantor'), ('officer', 'Loan officer'), ('branch_manager', 'Branch manager')], db_index=True, max_length=24)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('otp_hash', models.CharField(max_length=128)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_phone', models.CharField(max_length=30)),
                ('signer_id_number', models.CharField(blank=True, max_length=80)),
                ('content_hash', models.CharField(help_text='Agreement content hash when OTP was issued.', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_challenges', to='loans.loanagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_remote_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
