# Generated by Django 3.2.25 on 2026-08-22 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0075_remote_otp_sign_and_image_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('case_type', models.CharField(choices=[('fraud', 'Fraud'), ('aml', 'AML / transaction monitoring')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('escalated', 'Escalated'), ('closed', 'Closed — confirmed'), ('false_positive', 'Closed — false positive')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=12)),
                ('source', models.CharField(choices=[('document_auth', 'Document authentication'), ('banking_anomaly', 'Banking / transaction anomaly'), ('manual', 'Manual referral'), ('digital_apply', 'Digital Apply'), ('disbursement', 'Disbursement')], db_index=True, max_length=24)),
                ('summary', models.CharField(max_length=500)),
                ('blocks_origination', models.BooleanField(default=True)),
                ('blocks_disbursement', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases_closed', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases', to='loans.loanrequestdocument')),
                ('loan_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_cases', to='loans.loanrequest')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_cases_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_engine_enabled', models.BooleanField(default=True, help_text='Master switch for auto-opening compliance cases and desk.')),
                ('anomaly_score_threshold', models.PositiveSmallIntegerField(default=60, help_text='Open AML case when transaction anomaly score ≥ this (0–100).')),
                ('anomaly_score_warn', models.PositiveSmallIntegerField(default=40, help_text='Surface warning in banking metrics below case threshold.')),
                ('auto_open_document_duplicate', models.BooleanField(default=True, help_text='Open fraud case when document SHA matches another loan file.')),
                ('auto_open_document_suspicious', models.BooleanField(default=True, help_text='Open fraud case when officer marks document suspicious.')),
                ('auto_open_banking_anomaly', models.BooleanField(default=True, help_text='Open AML case when banking anomaly score exceeds threshold.')),
                ('require_compliance_clear_before_committee', models.BooleanField(default=True, help_text='Block committee submit while open fraud/AML cases block origination.')),
                ('require_compliance_clear_before_disbursement', models.BooleanField(default=True, help_text='Block disbursement while open cases block disbursement.')),
            ],
            options={
                'verbose_name': 'Compliance policy',
                'verbose_name_plural': 'Compliance policy',
            },
        ),
        migrations.AlterField(
            model_name='loannotification',
            name='kind',
            field=models.CharField(choices=[('vote_needed', 'Vote needed'), ('level_advanced', 'Advanced to next level'), ('committee_approved', 'Committee approved'), ('committee_declined', 'Committee declined'), ('returned_to_officer', 'Returned to loan officer'), ('document_uploaded', 'Document uploaded'), ('document_needs_review', 'Document needs review'), ('document_verified', 'Document verified'), ('document_rejected', 'Document rejected'), ('document_requested', 'Document requested'), ('collateral_assigned', 'Collateral assigned'), ('collateral_submitted', 'Collateral submitted'), ('collateral_engineering_return', 'Collateral returned by engineering'), ('collateral_engineering_approved', 'Collateral approved by engineering'), ('disbursement_ready', 'Ready for disbursement'), ('disbursed', 'Disbursed'), ('compliance_case_opened', 'Compliance case opened')], max_length=40),
        ),
        migrations.CreateModel(
            name='TransactionAnomalyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('risk_band', models.CharField(db_index=True, default='low', max_length=16)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appraisal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_anomaly_assessments', to='loans.loanappraisal')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_anomaly_assessments', to='loans.loanrequest')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('opened', 'Opened'), ('note', 'Note'), ('status_change', 'Status change'), ('assignment', 'Assignment'), ('escalation', 'Escalation'), ('evidence', 'Evidence')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='loans.compliancecase')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_case_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compliancecase',
            index=models.Index(fields=['status', 'priority'], name='loans_compl_status_ba80ec_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecase',
            index=models.Index(fields=['loan_request', 'status'], name='loans_compl_loan_re_38e3f1_idx'),
        ),
    ]
