# Generated by Django 3.2.25 on 2026-08-25 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0076_fraud_aml_case_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprocesspolicyconfig',
            name='require_legal_clearance',
            field=models.BooleanField(default=True, help_text='Bank-wide: Legal Administration must clear the file before disbursement when any collateral legal paper is required.'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='legal_clearance_note',
            field=models.TextField(blank=True, help_text='Legal Administration clearance or return note.'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='legal_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='legal_cleared_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'legal_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_requests_legal_cleared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalcommitteelevel',
            name='tiebreaker_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Administrator'), ('admin', 'System Administrator'), ('engineering_head', 'Engineering Head'), ('engineer', 'Engineer / Valuer'), ('loan_officer', 'Loan Officer'), ('branch_manager', 'Branch Manager'), ('accountant', 'Accountant'), ('district_manager', 'District Manager'), ('cooperative_manager', 'Branch Cooperative Manager'), ('finance_manager', 'Finance Manager'), ('credit_head', 'Credit Department Head'), ('credit_loan_officer', 'Credit Loan Officer'), ('ceo', 'Chief Executive Officer'), ('vp', 'Vice President'), ('vp_operations', 'VP Operations'), ('vp_it', 'VP IT'), ('vp_customer_service', 'VP Customer Service'), ('board_member', 'Board Member'), ('risk_compliance', 'Risk & Compliance Officer'), ('legal_officer', 'Legal Officer'), ('auditor', 'Auditor / Viewer'), ('operation_manager', 'Operation Manager (legacy)'), ('credit_committee', 'Credit Committee Member (legacy)')], help_text='When approve and decline votes are equal, this role’s vote decides. Defaults by level: branch→branch_manager, district→district_manager, head_office→credit_head, management→board_member then ceo.', max_length=30),
        ),
        migrations.AlterField(
            model_name='approvalcommitteememberrule',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Administrator'), ('admin', 'System Administrator'), ('engineering_head', 'Engineering Head'), ('engineer', 'Engineer / Valuer'), ('loan_officer', 'Loan Officer'), ('branch_manager', 'Branch Manager'), ('accountant', 'Accountant'), ('district_manager', 'District Manager'), ('cooperative_manager', 'Branch Cooperative Manager'), ('finance_manager', 'Finance Manager'), ('credit_head', 'Credit Department Head'), ('credit_loan_officer', 'Credit Loan Officer'), ('ceo', 'Chief Executive Officer'), ('vp', 'Vice President'), ('vp_operations', 'VP Operations'), ('vp_it', 'VP IT'), ('vp_customer_service', 'VP Customer Service'), ('board_member', 'Board Member'), ('risk_compliance', 'Risk & Compliance Officer'), ('legal_officer', 'Legal Officer'), ('auditor', 'Auditor / Viewer'), ('operation_manager', 'Operation Manager (legacy)'), ('credit_committee', 'Credit Committee Member (legacy)')], help_text='For branch: user must belong to the loan branch. For district: loan district.', max_length=30),
        ),
        migrations.AlterField(
            model_name='branchcommitteememberrule',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Administrator'), ('admin', 'System Administrator'), ('engineering_head', 'Engineering Head'), ('engineer', 'Engineer / Valuer'), ('loan_officer', 'Loan Officer'), ('branch_manager', 'Branch Manager'), ('accountant', 'Accountant'), ('district_manager', 'District Manager'), ('cooperative_manager', 'Branch Cooperative Manager'), ('finance_manager', 'Finance Manager'), ('credit_head', 'Credit Department Head'), ('credit_loan_officer', 'Credit Loan Officer'), ('ceo', 'Chief Executive Officer'), ('vp', 'Vice President'), ('vp_operations', 'VP Operations'), ('vp_it', 'VP IT'), ('vp_customer_service', 'VP Customer Service'), ('board_member', 'Board Member'), ('risk_compliance', 'Risk & Compliance Officer'), ('legal_officer', 'Legal Officer'), ('auditor', 'Auditor / Viewer'), ('operation_manager', 'Operation Manager (legacy)'), ('credit_committee', 'Credit Committee Member (legacy)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('admin', 'System Administrator'), ('engineering_head', 'Engineering Head'), ('engineer', 'Engineer / Valuer'), ('loan_officer', 'Loan Officer'), ('branch_manager', 'Branch Manager'), ('accountant', 'Accountant'), ('district_manager', 'District Manager'), ('cooperative_manager', 'Branch Cooperative Manager'), ('finance_manager', 'Finance Manager'), ('credit_head', 'Credit Department Head'), ('credit_loan_officer', 'Credit Loan Officer'), ('ceo', 'Chief Executive Officer'), ('vp', 'Vice President'), ('vp_operations', 'VP Operations'), ('vp_it', 'VP IT'), ('vp_customer_service', 'VP Customer Service'), ('board_member', 'Board Member'), ('risk_compliance', 'Risk & Compliance Officer'), ('legal_officer', 'Legal Officer'), ('auditor', 'Auditor / Viewer'), ('operation_manager', 'Operation Manager (legacy)'), ('credit_committee', 'Credit Committee Member (legacy)')], default='loan_officer', max_length=30),
        ),
    ]
