# Generated by Django 3.2.25 on 2026-08-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0077_legal_admin_desk_clearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancepolicy',
            name='auto_open_pep_hit',
            field=models.BooleanField(default=True, help_text='Open sanctions/PEP case when subject matches a PEP list.'),
        ),
        migrations.AddField(
            model_name='compliancepolicy',
            name='auto_open_sanctions_hit',
            field=models.BooleanField(default=True, help_text='Open sanctions case when name / customer number hits a sanctions list.'),
        ),
        migrations.AlterField(
            model_name='compliancecase',
            name='case_type',
            field=models.CharField(choices=[('fraud', 'Fraud'), ('aml', 'AML / transaction monitoring'), ('sanctions', 'Sanctions / PEP')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='compliancecase',
            name='source',
            field=models.CharField(choices=[('document_auth', 'Document authentication'), ('banking_anomaly', 'Banking / transaction anomaly'), ('manual', 'Manual referral'), ('digital_apply', 'Digital Apply'), ('disbursement', 'Disbursement'), ('name_screen', 'Sanctions / PEP screening')], db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='SanctionsScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.BooleanField(db_index=True, default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('match_types', models.JSONField(blank=True, default=list)),
                ('matches', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, max_length=24)),
                ('subject', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('screened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('compliance_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_screenings', to='loans.compliancecase')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_screenings', to='loans.loanrequest')),
            ],
            options={
                'ordering': ['-screened_at'],
            },
        ),
    ]
