# Generated by Django 3.2.25 on 2026-09-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0092_wholesale_murabaha_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycIdentityCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('clear', 'Clear'), ('review', 'Review'), ('blocked', 'Blocked')], db_index=True, default='review', max_length=12)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_identity_case', to='loans.loanrequest')),
            ],
            options={
                'verbose_name': 'KYC identity case',
                'verbose_name_plural': 'KYC identity cases',
            },
        ),
        migrations.AddField(
            model_name='documentauthenticationpolicy',
            name='block_fee_on_strict_identity_fail',
            field=models.BooleanField(default=True, help_text='Digital Apply: National ID / TIN uploads that fail quality or identity cannot proceed to the processing fee.'),
        ),
        migrations.AlterField(
            model_name='loanappraisal',
            name='appraisal_mode',
            field=models.CharField(choices=[('msme', 'MSME / cashflow sheets'), ('corporate', 'Corporate / financial statements'), ('project', 'Project desk (viability, equity, plant)'), ('wholesale', 'Wholesale / PFI institution desk'), ('lease', 'Lease / hire-purchase asset desk'), ('ifb_murabaha', 'Murabaha cost-plus desk'), ('ifb_ijarah', 'Ijarah rental desk'), ('idea_equity', 'Idea / quasi-equity desk'), ('consumer', 'Consumer / HRM scorecard')], db_index=True, default='msme', help_text='Copied from the loan type. Product desks are not the 7-sheet wizard.', max_length=20),
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='allowed_collateral',
            field=models.ManyToManyField(blank=True, help_text='Security types this product may use. Ignored when collateral is not required.', related_name='loan_categories', to='loans.CollateralType'),
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='product_family',
            field=models.CharField(choices=[('general', 'General (MSME / corporate)'), ('project', 'Project financing'), ('lease', 'Lease financing'), ('wholesale', 'Wholesale / PFI facility'), ('consumer', 'Consumer (housing / vehicle)'), ('ifb_murabaha', 'IFB — Murabaha'), ('ifb_ijarah', 'IFB — Ijarah'), ('external_fund', 'External fund window'), ('idea_equity', 'Idea / quasi-equity')], db_index=True, default='general', help_text='Lifecycle overlay (project, lease, IFB, …). MSME/corporate sheets apply only to general.', max_length=20),
        ),
        migrations.CreateModel(
            name='KycParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('director', 'Director'), ('ubo', 'Beneficial owner'), ('guarantor', 'Guarantor'), ('spouse', 'Spouse')], db_index=True, default='applicant', max_length=16)),
                ('legal_name_en', models.CharField(blank=True, max_length=255)),
                ('legal_name_am', models.CharField(blank=True, max_length=255)),
                ('identity_kind', models.CharField(choices=[('fayda_fan', 'Fayda (FAN)'), ('national_id', 'National ID'), ('kebele', 'Kebele ID'), ('passport', 'Passport'), ('tin', 'TIN'), ('license', 'Business license')], default='national_id', max_length=20)),
                ('fan', models.CharField(blank=True, max_length=40)),
                ('tin', models.CharField(blank=True, max_length=40)),
                ('id_number', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('verify_status', models.CharField(choices=[('pending', 'Not verified'), ('confirmed', 'Confirmed'), ('not_found', 'Not found'), ('mismatch', 'Mismatch'), ('provider_error', 'Provider error'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('verify_payload', models.JSONField(blank=True, default=dict)),
                ('biometric_status', models.CharField(blank=True, choices=[('', 'Not captured'), ('pending', 'Pending'), ('matched', 'Matched'), ('failed', 'Failed')], default='', max_length=16)),
                ('face_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('liveness_ref', models.CharField(blank=True, max_length=80)),
                ('share_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership share for UBO / director (phase 3).', max_digits=6, null=True)),
                ('capacity', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='loans.kycidentitycase')),
            ],
            options={
                'verbose_name': 'KYC party',
                'verbose_name_plural': 'KYC parties',
                'ordering': ['id'],
            },
        ),
    ]
