#!/usr/bin/env bash
# DECSI / Dedebit — simple on-prem install from this GitHub repo.
#
# Usage (on the server):
#   git clone https://github.com/habenkiros/decsi_loan.git
#   cd decsi_loan
#   ./scripts/install_decsi.sh
#
# Optional env before running:
#   LICENSE_KEY='SEQLA1.…'     # or place key in deploy/license/license.key
#   WEB_PORT=8000
#   CREATE_SUPERUSER=1         # prompt to create admin (default: ask)
#   NONINTERACTIVE=1           # skip prompts; still creates .env + starts stack
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

RED=$'\033[31m'
GRN=$'\033[32m'
YLW=$'\033[33m'
BLD=$'\033[1m'
RST=$'\033[0m'

say() { echo "${BLD}$*${RST}"; }
ok() { echo "${GRN}✓${RST} $*"; }
warn() { echo "${YLW}!${RST} $*"; }
die() { echo "${RED}✗${RST} $*" >&2; exit 1; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing dependency: $1"
}

detect_host() {
  if [[ -n "${SITE_HOST:-}" ]]; then
    echo "$SITE_HOST"
    return
  fi
  # Prefer first non-loopback IPv4
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  if [[ -n "$ip" ]]; then
    echo "$ip"
    return
  fi
  echo "127.0.0.1"
}

gen_secret() {
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import secrets; print(secrets.token_urlsafe(50))'
  else
    head -c 48 /dev/urandom | base64 | tr -d '\n+/=' | head -c 64
  fi
}

resolve_license() {
  if [[ -n "${LICENSE_KEY:-}" ]]; then
    echo "$LICENSE_KEY"
    return
  fi
  local f
  for f in \
    "$ROOT/deploy/license/license.key" \
    "$ROOT/docs/deployment/DEDEbit_LICENSE_KEY_7DAY.txt" \
    "$ROOT/docs/deployment/DEDEbit_LICENSE_KEY_YEAR1.txt"
  do
    if [[ -f "$f" ]]; then
      # first non-empty non-comment line
      awk 'NF && $0 !~ /^#/ {print; exit}' "$f"
      return
    fi
  done
  echo ""
}

say "DECSI Loan Hub — simple install"
echo "Repo: $ROOT"
echo

need_cmd docker
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 required (docker compose …)"

HOST="$(detect_host)"
PORT="${WEB_PORT:-8000}"
LICENSE="$(resolve_license | tr -d '\r' | head -n1)"

if [[ -z "$LICENSE" ]]; then
  warn "No LICENSE_KEY found yet."
  warn "Set LICENSE_KEY=SEQLA1.… or put the key in deploy/license/license.key"
  if [[ "${NONINTERACTIVE:-0}" != "1" ]]; then
    read -r -p "Paste LICENSE_KEY now (or Enter to continue without): " LICENSE || true
  fi
fi

if [[ ! -f .env ]]; then
  say "Creating .env …"
  SECRET="$(gen_secret)"
  DBPASS="$(gen_secret | head -c 24)"
  cat > .env <<EOF
# Generated by scripts/install_decsi.sh — $(date -u +%Y-%m-%dT%H:%MZ)
SECRET_KEY=${SECRET}
DEBUG=False
ALLOWED_HOSTS=localhost,127.0.0.1,${HOST}
SITE_URL=http://${HOST}:${PORT}
WEB_PORT=${PORT}

DB_NAME=decsiloandb
DB_USER=decsiloandbuser
DB_PASSWORD=${DBPASS}
DB_HOST=db
DB_PORT=5432

LICENSE_KEY=${LICENSE}
LICENSE_ENFORCE=True
LICENSE_GRACE_DAYS=7

LOGIN_MAX_FAILED_ATTEMPTS=5
LOGIN_LOCKOUT_MINUTES=15
MFA_REQUIRED=False
MFA_TOTP_ISSUER=DECSI Loan Hub
SESSION_IDLE_TIMEOUT=1800

DECSI_CUSTOMER_FALLBACK_MOCK=True
DECSI_CBS_USE_MOCK_LEDGER=True
CHAPA_FORCE_MOCK=True
DOCUMENT_OCR_LANG=eng+amh
EOF
  ok "Wrote .env (DEBUG=False, mocks on for pilot)"
else
  ok ".env already exists — leaving it unchanged"
  if [[ -n "$LICENSE" ]] && ! grep -q '^LICENSE_KEY=SEQLA1' .env 2>/dev/null; then
    if grep -q '^LICENSE_KEY=' .env; then
      # replace empty/placeholder
      if grep -qE '^LICENSE_KEY=\s*$|^LICENSE_KEY=replace' .env; then
        sed -i.bak "s|^LICENSE_KEY=.*|LICENSE_KEY=${LICENSE}|" .env
        ok "Filled LICENSE_KEY in existing .env"
      fi
    else
      echo "LICENSE_KEY=${LICENSE}" >> .env
      ok "Appended LICENSE_KEY to .env"
    fi
  fi
fi

if [[ -n "$LICENSE" ]]; then
  mkdir -p deploy/license
  printf '%s\n' "$LICENSE" > deploy/license/license.key
  ok "Saved deploy/license/license.key"
fi

say "Building and starting Docker stack (first run can take several minutes)…"
docker compose up --build -d

say "Waiting for database…"
for i in $(seq 1 60); do
  if docker compose exec -T db pg_isready -U "${DB_USER:-decsiloandbuser}" -d "${DB_NAME:-decsiloandb}" >/dev/null 2>&1; then
    ok "Database is ready"
    break
  fi
  if [[ "$i" -eq 60 ]]; then
    die "Database did not become ready — check: docker compose logs db"
  fi
  sleep 2
done

say "Running migrations…"
docker compose exec -T web python manage.py migrate --noinput
ok "Migrations applied"

say "License check…"
docker compose exec -T -e LICENSE_ENFORCE=True web python manage.py check_license || warn "License check reported an issue — open /license/ after start"

CREATE="${CREATE_SUPERUSER:-}"
if [[ -z "$CREATE" && "${NONINTERACTIVE:-0}" != "1" ]]; then
  read -r -p "Create a superuser now? [Y/n] " ans || true
  ans="${ans:-Y}"
  if [[ "$ans" =~ ^[Yy]$ ]]; then
    CREATE=1
  fi
fi
if [[ "${CREATE:-0}" == "1" ]]; then
  docker compose exec -it web python manage.py createsuperuser || warn "Superuser step skipped or failed"
fi

echo
say "Install complete"
echo
echo "  Staff hub:      http://${HOST}:${PORT}/hub/login/"
echo "  Digital Apply:  http://${HOST}:${PORT}/"
echo "  License status: http://${HOST}:${PORT}/license/"
echo "  Help / manuals: http://${HOST}:${PORT}/hub/help/"
echo
echo "Useful commands:"
echo "  docker compose ps"
echo "  docker compose logs -f web"
echo "  docker compose restart web"
echo
echo "Full guide: docs/deployment/DEDEBIT_ON_PREM_INSTALLATION.md"
echo "After commercial agreement: replace LICENSE_KEY with the Year-1 key and restart web."
echo
